add_library(AvsVideoConvert STATIC src/resize.cpp src/matrix.cpp src/depth.cpp src/dither.cpp)
set_target_properties(AvsVideoConvert PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_compile_features(AvsVideoConvert PRIVATE cxx_std_17)
target_compile_definitions(AvsVideoConvert PRIVATE BUILDING_AVSCORE)
if(NOT BUILD_SHARED_LIBS)
  target_compile_definitions(AvsVideoConvert PRIVATE AVS_STATIC_LIB)
endif()
target_link_libraries(AvsVideoConvert PRIVATE AviSynth::ConvertVideo AvsSimd)
target_include_directories(AvsVideoConvert PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include")
