add_library(AvsComposite STATIC src/layer.cpp)
set_target_properties(AvsComposite PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_compile_features(AvsComposite PUBLIC cxx_std_17)
target_compile_definitions(AvsComposite PRIVATE BUILDING_AVSCORE)
if(NOT BUILD_SHARED_LIBS)
  target_compile_definitions(AvsComposite PRIVATE AVS_STATIC_LIB)
endif()
target_include_directories(AvsComposite PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include")
target_link_libraries(AvsComposite PUBLIC AviSynth::Composite AvsSimd)
